add_newline = true
# A minimal left prompt
format = '$all'
palette = "kanagawa"

[character]
success_symbol = '[❯](oni_violet)'
error_symbol = '[❯](wave_red) '

[directory]
format = '[$path ]($style)'
style = "crystal_blue"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[git_branch]
symbol = " "
style = "oni_violet"
format = 'on [$symbol$branch ]($style)'

[git_status]
format = '[($all_status$ahead_behind)]($style)'
style = "carp_yellow"

[cmd_duration]
disabled = true

[c]
disabled = true
symbol = " "
format = ' [$symbol $version ]($style)'
style = 'crystal_blue'
commands = [ [ 'clang', '--version' ] ]

[nodejs]
disabled = true
symbol = ""
format = '[$symbol( $version )]($style)'
style = "spring_green"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold crystal_blue'
symbol = " "

[rust]
disabled = true
symbol = ""
format = '[ $symbol( $version )]($style)'

[lua]
disabled = true
format = 'via [🌕 $version](bold crystal_blue) '

[golang]
disabled = true
symbol = ""
format = '[ $symbol( $version) ]($style)'
detect_files = ["go.mod"]
style = "bold spring_blue"

[php]
disabled = true
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[java]
disabled = true
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[kotlin]
disabled = true
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[haskell]
disabled = true
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[python]
disabled = true
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "spring_green", context_alias = "Glock", symbol = " " },
]

[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'

[conda]
disabled = true

[palettes.kanagawa]
fuji_white = "#DCD7BA"    # Text
samurai_red = "#C34043"   # Red
sakura_pink = "#D27E99"   # Pink
carp_yellow = "#E6C384"   # Yellow
spring_green = "#98BB6C"  # Green
crystal_blue = "#7E9CD8"  # Blue
spring_blue = "#7FB4CA"   # Cyan/Teal
surimi_orange = "#FF9E64" # Orange
oni_violet = "#957FB8"    # Purple/Lavender
wave_red = "#E46876"      # Error/Danger
sumi_ink = "#54546D"      # Dark/Muted
